# Generated by Django 6.1 on 2026-09-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openoutreach_config', '0002_rename_operator_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='accepted_legal_notice',
        ),
    ]
